name: Release CI
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  #################################################
  ## Cross platform binary build for release page #
  #################################################

  cross_platform_build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            output_name: linux_x86_64.tar.gz

          - target: aarch64-unknown-linux-musl
            output_name: linux_aarch64.tar.gz

          - target: arm-unknown-linux-musleabihf
            output_name: linux_armv6.tar.gz

          - target: aarch64-apple-darwin
            output_name: apple_darwin_aarch64.tar.gz

          - target: x86_64-pc-windows-gnu
            output_name: windows_x86_64.zip

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install stable rust, and associated tools
      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      # Install cross-rs
      - name: install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      # Build binary for arm MacOS using Docker Zigbuild
      - name: build
        if: matrix.target == 'aarch64-apple-darwin'
        run: |
          docker run --rm -v $(pwd):/io -w /io ghcr.io/rust-cross/cargo-zigbuild cargo zigbuild --release --target aarch64-apple-darwin

      # Build all other targets using Cross
      - name: build
        if: matrix.target != 'aarch64-apple-darwin'
        run: cross build --target ${{ matrix.target }} --release

      # Compress the Windows binary into a .zip
      - name: compress windows
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: |
          zip -j "./oxker_${{ matrix.output_name }}" target/${{ matrix.target }}/release/oxker.exe

      # Compress all other binaries into .tar.gz
      - name: compress linux
        if: matrix.target != 'x86_64-pc-windows-gnu'
        run: |
          tar -C "target/${{ matrix.target }}/release" -czf "./oxker_${{ matrix.output_name }}" oxker

      # Upload output for release page
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: ${{ matrix.target }}
          path: oxker_${{ matrix.output_name }}
          retention-days: 1

  ###################
  ## Create release #
  ###################

  create_release:
    needs: [cross_platform_build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup | Artifacts
        uses: actions/download-artifact@v4

      - name: Update Release
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true
          name: ${{ github.ref_name }}
          tag: ${{ github.ref }}
          bodyFile: ".github/release-body.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            **/oxker_*.zip
            **/oxker_*.tar.gz

